# site settings

title: RobotClowns
description: An awesome kid who deserves the world
taglong: Happy Birthday! I hope you like this!
tagshort: Westin
url: https://robotclowns.com
baseurl: ""
permalink: pretty
repo: https://github.com/robotclowns

# author settings

author:
  name: Westin
  email: dancingplums@gmail.com
photo: /assets/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
